### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by PowerSchill** [nemccarthy/stash-pullrequest-builder-plugin#152]
I've downloaded and compiled version 1.7.1 from source. When I install it I start getting this error message repeating. Any ideas on the cause and fix?

```
Oct 15, 2018 6:02:00 AM WARNING hudson.triggers.Trigger checkTriggers
stashpullrequestbuilder.stashpullrequestbuilder.StashBuildTrigger.run() failed for org.jenkinsci.plugins.workflow.job.WorkflowJob@6d10fbe9[cookbooks/prt/job-prtt]
java.lang.NullPointerException
	at stashpullrequestbuilder.stashpullrequestbuilder.StashBuildTrigger.run(StashBuildTrigger.java:295)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by proski** [comment]
I'm quite sure the issue was addressed in https://github.com/jenkinsci/stash-pullrequest-builder-plugin/pull/48
That PR has been merged, but it's not part of any release yet.

**Comment by nemccarthy** [comment]
This was fixed in the offical repo now. Closing this
