### ISSUE TITLE
Unit Test failure on OSX

### ISSUE THREAD

**Issue by dalewking** [nemccarthy/stash-pullrequest-builder-plugin#25]
Unit tests failing on OSX:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running InjectedTest
Picking up existing exploded jenkins.war at /Users/DALEK/stash-pullrequest-builder-plugin/./target/jenkins-for-test
Jul 01, 2015 10:54:32 PM org.mortbay.log.Slf4jLog info
INFO: Logging to org.slf4j.impl.JDK14LoggerAdapter(org.mortbay.log) via org.mortbay.log.Slf4jLog
Jul 01, 2015 10:54:33 PM org.mortbay.log.Slf4jLog info
INFO: jetty-6.1.26
Jul 01, 2015 10:54:33 PM org.mortbay.log.Slf4jLog info
INFO: NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
Jul 01, 2015 10:54:33 PM org.mortbay.log.Slf4jLog info
INFO: Started SocketConnector@0.0.0.0:49599
Jul 01, 2015 10:54:33 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Jul 01, 2015 10:54:35 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Jul 01, 2015 10:54:35 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Jul 01, 2015 10:54:35 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Jul 01, 2015 10:54:35 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Jul 01, 2015 10:54:35 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Jul 01, 2015 10:54:36 PM net.java.sezpoz.Index$LazyIndexIterator peek
WARNING: possible endless loop getting index for interface hudson.Extension from classLoader hudson.PluginManager$UberClassLoader
Jul 01, 2015 10:54:36 PM net.java.sezpoz.Index$LazyIndexIterator peek
WARNING: possible endless loop getting index for interface hudson.Extension from classLoader hudson.PluginManager$UberClassLoader
Jul 01, 2015 10:54:37 PM net.java.sezpoz.Index$LazyIndexIterator peek
WARNING: possible endless loop getting index for interface hudson.Extension from classLoader hudson.PluginManager$UberClassLoader
Jul 01, 2015 10:54:38 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed GitTool.onLoaded
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.InitializerFinder.invoke(InitializerFinder.java:124)
	at hudson.init.InitializerFinder$TaskImpl.run(InitializerFinder.java:184)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:899)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at hudson.init.InitializerFinder.invoke(InitializerFinder.java:120)
	... 8 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at com.thoughtworks.xstream.core.util.OrderRetainingMap.entrySet(OrderRetainingMap.java:77)
	at java.util.HashMap.putMapEntries(HashMap.java:511)
	at java.util.HashMap.putAll(HashMap.java:784)
	at com.thoughtworks.xstream.core.util.OrderRetainingMap.<init>(OrderRetainingMap.java:36)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildMap(FieldDictionary.java:135)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.fieldsFor(FieldDictionary.java:76)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:127)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:143)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:102)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:898)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:887)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:860)
	at hudson.XmlFile.write(XmlFile.java:183)
	at hudson.model.Descriptor.save(Descriptor.java:758)
	at hudson.plugins.git.GitTool.onLoaded(GitTool.java:106)
	... 13 more

Exception in thread "pool-2-thread-3" java.lang.NullPointerException
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-2-thread-10" java.lang.NullPointerException
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-2-thread-1" java.lang.NullPointerException
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-2-thread-7" java.lang.NullPointerException
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-2-thread-2" java.lang.NullPointerException
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-2-thread-5" java.lang.NullPointerException
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Jul 01, 2015 10:54:38 PM org.mortbay.log.Slf4jLog info
INFO: jetty-6.1.26
Jul 01, 2015 10:54:38 PM org.mortbay.log.Slf4jLog info
INFO: NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
Jul 01, 2015 10:54:38 PM org.mortbay.log.Slf4jLog info
INFO: Started SocketConnector@0.0.0.0:49634
Jul 01, 2015 10:54:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Jul 01, 2015 10:54:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Jul 01, 2015 10:54:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Jul 01, 2015 10:54:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Jul 01, 2015 10:54:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Jul 01, 2015 10:54:39 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
Jul 01, 2015 10:54:39 PM net.java.sezpoz.Index$LazyIndexIterator peek
WARNING: possible endless loop getting index for interface hudson.Extension from classLoader hudson.PluginManager$UberClassLoader
Jul 01, 2015 10:54:39 PM net.java.sezpoz.Index$LazyIndexIterator peek
WARNING: possible endless loop getting index for interface hudson.Extension from classLoader hudson.PluginManager$UberClassLoader
Jul 01, 2015 10:54:39 PM net.java.sezpoz.Index$LazyIndexIterator peek
WARNING: possible endless loop getting index for interface hudson.Extension from classLoader hudson.PluginManager$UberClassLoader
Jul 01, 2015 10:54:40 PM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed GitTool.onLoaded
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.InitializerFinder.invoke(InitializerFinder.java:124)
	at hudson.init.InitializerFinder$TaskImpl.run(InitializerFinder.java:184)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:899)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at hudson.init.InitializerFinder.invoke(InitializerFinder.java:120)
	... 8 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at com.thoughtworks.xstream.core.util.OrderRetainingMap.entrySet(OrderRetainingMap.java:77)
	at java.util.HashMap.putMapEntries(HashMap.java:511)
	at java.util.HashMap.putAll(HashMap.java:784)
	at com.thoughtworks.xstream.core.util.OrderRetainingMap.<init>(OrderRetainingMap.java:36)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildMap(FieldDictionary.java:135)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.fieldsFor(FieldDictionary.java:76)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:127)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:143)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:102)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:898)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:887)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:860)
	at hudson.XmlFile.write(XmlFile.java:183)
	at hudson.model.Descriptor.save(Descriptor.java:758)
	at hudson.plugins.git.GitTool.onLoaded(GitTool.java:106)
	... 13 more

Exception in thread "pool-6-thread-15" java.lang.NullPointerException
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-6-thread-9" Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 9.195 sec <<< FAILURE!
Exception in thread "pool-6-thread-5" Running stashpullrequestbuilder.stashpullrequestbuilder.stash.StashApiClientTest
Exception in thread "pool-6-thread-2" Exception in thread "pool-6-thread-14" java.lang.NullPointerException
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-6-thread-12" java.lang.NullPointerException
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.224 sec
Running stashpullrequestbuilder.stashpullrequestbuilder.stash.StashPullRequestResponseValueRepositoryTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec

Results :

Tests in error: 
  org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite(org.jvnet.hudson.test.junit.FailedTest): java.lang.Error: java.lang.reflect.InvocationTargetException
  testCliSanity(org.jvnet.hudson.test.PluginAutomaticTestBuilder$CliSanityTest): java.lang.Error: java.lang.reflect.InvocationTargetException

Tests run: 8, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by laurentverbruggen** [comment]
I don't have any issues on Yosemite, when I execute mvn clean verify.

**Comment by dalewking** [comment]
And I get that every time on Yosemite. I would be happy to run any test code to try to figure it out, but I have no time to try to debug it for you.

**Comment by nemccarthy** [comment]
Ditto on running with Mac Yosemite. Make sure you're running with Java 7!
